import { readFileSync, existsSync } from 'node:fs';
import { extname, join } from 'node:path';
import { buildApi } from './apps/server/src/api.js';
import { Store } from './apps/server/src/db.js';
import { Pipeline } from './apps/server/src/pipeline.js';
const { chromium } = await import('/opt/node22/lib/node_modules/playwright/index.mjs');
const DIST = join(process.cwd(), 'apps/web/dist');
const T: Record<string,string> = { '.html':'text/html','.js':'text/javascript','.css':'text/css' };
const store = new Store(':memory:');
const pipeline = new Pipeline([], store, { market_limit: 1, stale_quote_ms: 9e9, min_net_edge: 1, history_retention_days: 1 });
const app = buildApi({ pipeline, store, adapters: [] });
app.get('/*', async (req, reply) => {
  const u = (req.params as any)['*'] || 'index.html';
  const path = join(DIST, u);
  const file = existsSync(path) && extname(path) ? path : join(DIST, 'index.html');
  reply.type(T[extname(file)] ?? 'text/plain').send(readFileSync(file));
});
await app.listen({ port: 8787, host: '127.0.0.1' });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1280, height: 2400 }, deviceScaleFactor: 2 });
const SP='/tmp/claude-0/-home-user-Efunny/0ed60727-a46c-52f1-9fe0-c12dc970c2ce/scratchpad';
await p.goto('http://127.0.0.1:8787/', { waitUntil: 'networkidle' });
await p.getByRole('button', { name: 'NFL', exact: true }).click();
await p.waitForSelector('.nfl-game', { timeout: 120000 });
await p.locator('.nfl-game').first().click();
await p.waitForSelector('.matchup', { timeout: 240000 });
await p.locator('.splits').scrollIntoViewIfNeeded();
await p.screenshot({ path: SP+'/nfl2.png' });
console.log('sections:', await p.locator('.matchup h4').allTextContents());
await b.close(); await app.close();
